version: '3'
services:
  # Postgresql DB Image
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    restart: always
    volumes:
    - ../postgresData:/var/lib/postgresql/data
    networks:
      - app-network
      
  # ted helper service
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
    - db
    networks:
      - app-network
      
  # ted simulator service
  ted-simulator:
     build:
       context: ../json-server/Dockerfile
     ports:
       - "3000:3000"
     networks:
       - app-network

networks:
  app-network:
    driver: bridge
